import { Users, BookOpen, Home, Briefcase, Heart, Gavel, FileText, Activity, AlertTriangle, Car } from 'lucide-react';

export const services = [
    {
        slug: 'mva',
        title: 'Motor Vehicle Accidents',
        description: 'Specialized assistance with Road Accident Fund claims and motor vehicle accident recovery.',
        longDescription: 'Our team specializes in Motor Vehicle Accident (MVA) claims, helping victims recover the compensation they deserve from the Road Accident Fund. We handle the entire process from claim lodgement to litigation.',
        icon: Car,
    },
    {
        slug: 'criminal-matters',
        title: 'Criminal Matters',
        description: '24/7 bail applications and criminal defense representation.',
        longDescription: 'Whether it is a DUI, assault, or theft charge, our attorneys will represent you in court. We provide urgent bail applications and rigorous defense strategies.',
        icon: Gavel,
    },
    {
        slug: 'medical-negligence',
        title: 'Medical Negligence',
        description: 'Recourse for malpractice if a doctor or hospital caused you harm.',
        longDescription: 'If you have suffered due to medical malpractice, we are here to fight for your rights. Our experienced team handles complex negligence claims against healthcare providers and institutions.',
        icon: Activity,
    },
    {
        slug: 'matrimonial-matters',
        title: 'Matrimonial Matters',
        description: 'Divorce, maintenance, and custody proceedings handled with sensitivity.',
        longDescription: 'We handle contested and uncontested divorces, maintenance disputes, and child custody matters with the sensitivity and strength they require.',
        icon: Heart,
    },
    {
        slug: 'consumer-matters',
        title: 'Consumer Matters',
        description: 'Protection against unfair business practices, defective goods, and credit disputes.',
        longDescription: 'We provide comprehensive legal assistance for consumer protection issues, including managing disputes with creditors, blacklisting removal, and ensuring fair treatment under the Consumer Protection Act.',
        icon: Users,
    },
    {
        slug: 'commercial',
        title: 'Commercial Matters',
        description: 'Business contracts, shareholder agreements, and dispute resolution.',
        longDescription: 'We support businesses of all sizes with contract drafting, dispute resolution, compliance, and corporate governance. Let us handle the legalities so you can focus on growth.',
        icon: Briefcase,
    },
    {
        slug: 'contractual-matters',
        title: 'Contractual Matters',
        description: 'Review and drafting of all personal and business agreements.',
        longDescription: 'Don\'t sign a lease, loan, or employment contract without our review. We ensure your agreements are legally sound and protect your interests.',
        icon: FileText,
    },
    {
        slug: 'last-will',
        title: 'Last Will & Testament',
        description: 'Drafting of valid wills and living trusts to protect your family.',
        longDescription: 'Ensure your family is protected and your wishes are honored after you\'re gone. We draft clear, valid wills and assist with living trusts.',
        icon: FileText,
    },
    {
        slug: 'estates',
        title: 'Winding up of Estate',
        description: 'Professional administration of deceased estates and trust management.',
        longDescription: 'Losing a loved one is difficult. We take the burden of estate administration off your shoulders, ensuring the winding up process is handled with dignity, speed, and accuracy.',
        icon: BookOpen,
    },
    {
        slug: 'personal-injury',
        title: 'Personal Injury Claims',
        description: 'Beyond RAF, we handle slip-and-fall claims and dog bites.',
        longDescription: 'If you have been injured in a public space due to negligence, dog bites, or slip-and-fall incidents, we can help you claim compensation for your injuries and losses.',
        icon: AlertTriangle,
    },
    {
        slug: 'labour-matters',
        title: 'Labour Matters',
        description: 'CCMA representation for unfair dismissals and retrenchments.',
        longDescription: 'We fight unfair dismissals, retrenchments, and workplace discrimination on your behalf. Our team represents employees at the CCMA and Labour Court.',
        icon: Users,
    },
    {
        slug: 'property',
        title: 'Property Law Matters',
        description: 'Lease disputes, eviction orders, and property transfer advice.',
        longDescription: 'Whether you are buying, selling, or leasing, our property law experts ensure seamless transactions. We handle transfer of ownership, lease disputes, and eviction proceedings with professionalism.',
        icon: Home,
    },
];
